OLED_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes


LTO_ENABLE = yes

QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE=yes
RGB_MATRIX_DRIVER = ws2812

CONVERT_TO = promicro_rp2040


VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = no
